install.packages('string.i', dependencies=TRUE)
install.packages('Rcpp', dependencies=TRUE)
install.packages('yhatr', dependencies=TRUE)
install.packages('ggplot2', dependencies=TRUE)
install.packages('plyr', dependencies=TRUE)
install.packages('reshape2', dependencies=TRUE)
install.packages('forecast', dependencies=TRUE)
install.packages('stringr', dependencies=TRUE)
install.packages('lubridate', dependencies=TRUE)
install.packages('randomForest', dependencies=TRUE)
install.packages('rpart', dependencies=TRUE)
install.packages('e1071', dependencies=TRUE)
install.packages('kknn', dependencies=TRUE)
install.packages('RPostgreSQL', dependencies=TRUE)
install.packages('data.table', dependencies=TRUE)
install.packages('sqldf', dependencies=TRUE)
install.packages('stringr', dependencies=TRUE)
install.packages('RMYSQL', dependencies=TRUE)
install.packages('RMongo', dependencies=TRUE)
install.packages('RODBC', dependencies=TRUE)
install.packages('RSQLite', dependencies=TRUE)
install.packages('qcc', dependencies=TRUE)
install.packages('nnet', dependencies=TRUE)
install.packages('igraph', dependencies=TRUE)
install.packages('caret', dependencies=TRUE)
install.packages('kernlab', dependencies=TRUE)
install.packages('glmnet', dependencies=TRUE)
install.packages('ROCR', dependencies=TRUE)
install.packages('gbm', dependencies=TRUE)
install.packages('party', dependencies=TRUE)
install.packages('arules', dependencies=TRUE)
install.packages('packrat', dependencies=TRUE)
install.packages('tree', dependencies=TRUE)
install.packages('RWeka', dependencies=TRUE)
install.packages('klaR', dependencies=TRUE)
install.packages('ipred', dependencies=TRUE)
install.packages('lars', dependencies=TRUE)
install.packages('earth', dependencies=TRUE)
install.packages('CORElearn', dependencies=TRUE)
install.packages('mboost', dependencies=TRUE)
install.packages('rJava', dependencies=TRUE)
install.packages('RJDBC', dependencies=TRUE)
install.packages('dplyr', dependencies=TRUE)
install.packages('tidyr', dependencies=TRUE)
install.packages('lazyeval', dependencies=TRUE)
install.packages(
  'printr',
  type = 'source',
  repos = c('http://yihui.name/xran', 'http://cran.rstudio.com')
)
install.packages('discretization', dependencies=TRUE)
install.packages('doMC', dependencies=TRUE)
install.packages('xlsx', dependencies=TRUE)


